version: '3.4'
services:
  db:
    image: mysql:8
    volumes:
      - ./dc_rest_api/mysql_custom.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./compose.env
    ports:
     - "63310:3306"
  dc_rest_api:
    build: ./dc_rest_api
    image: dc_rest_api
    env_file:
      - ./compose.env
    ports:
      - "6561:6561"
    depends_on:
      - db




    
    
