version: '3.4'
services:
  db:
    image: mysql:8
    volumes:
      - ./dc_rest_api/mysql_custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/var/lib/mysql:delegated
    env_file:
      - ./compose.env
    ports:
     - "63312:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  dc_rest_api:
    build: ./dc_rest_api
    image: docker.leibniz-lib.de:5000/dc_rest_api
    env_file:
      - ./compose.env
    ports:
      - "${PYRAMID_PORT}:${PYRAMID_PORT}"
    depends_on:
      db:
        condition: service_healthy




    
    
