version: '3.4'
services:
  db:
    image: mysql:8
    volumes:
      - /var/data/dc_rest_api/mysql_custom.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./compose.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dc_rest_api_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.hostname == ganapti
      restart_policy:
        condition: any

  dc_rest_api:
    image: docker.leibniz-lib.de:5000/dc_rest_api
    ports:
      - "6561:6561"
    networks:
      - dc_rest_api_net
    env_file:
      - ./compose.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.hostname==ganapti
      restart_policy:
        condition: any

networks:
  dc_rest_api_net:
    driver: overlay




    
    
